name: CICD workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code 
      uses: actions/checkout@v2
    - name: We are testing this workflow
      run: echo Hello everyone!
