name: combined

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest 

    strategy:
      matrix:
      python-version: [3.11, 3.12, 3.13]


    steps:
    - name: checkout code
      uses: actions/checkout@v2 

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: install dependencies
      run: | 
        cd chapter4
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: run tests
      run:  |
        cd  chapter4
        python -m unittest discover

    - name: notify us of success
      run: echo "Tests" passed on Python ${{matrix.python-version}}"
      if: success()       